import mysql.connector

# Configuración de la base de datos MySQL
db_config = {
    'host': 'localhost',
    'user': 'root',  # Cambia esto si usaste otro usuario
    'password': 'D136o.84',  # Cambia esto por tu contraseña
    'database': 'cuestionario_db'
}

# Lista completa de opciones en formato [(idO, texto, idP), ...]
opciones = sorted([
    ("1A", "Conduzco en ciudad.", 1),
    ("1B", "La carretera está en mal estado.", 1),
    ("1C", "Llevo vidas bajo mi responsabilidad.", 1),
    ("1D", "He tomado unas copas.", 1),
    ("2A", "Ante otros conductores que me llaman la atención o me hacen una “faena”.", 2),
    ("2B", "Cuando se me cala el coche y me pitan los de atrás.", 2),
    ("2C", "Con los acompañantes que constantemente me dicen lo que debo hacer y me advierten de las normas de circulación.", 2),
    ("2D", "Ante peatones osados.", 2),
    ("3A", "Tengo que llegar pronto a alguna parte.", 3),
    ("3B", "Voy detrás de un vehículo que circula lentamente y me impide adelantarle.", 3),
    ("3C", "Me encuentro con atascos o algún contratiempo.", 3),
    ("3D", "En zona urbana tengo que detenerme ante los pasos de peatones.", 3),
    ("4A", "Soy paciente.", 4),
    ("4B", "Soy enérgico.", 4),
    ("4C", "Soy prudente.", 4),
    ("4D", "Soy impaciente.", 4),
    ("5A", "Conductores muy lentos.", 5),
    ("5B", "Conductores muy rápidos.", 5),
    ("5C", "Conductores agresivos.", 5),
    ("5D", "Conductores indecisos.", 5),
    ("6A", "Exceso de velocidad.", 6),
    ("6B", "Frenazos bruscos.", 6),
    ("6C", "Cambios de carril sin señalizar.", 6),
    ("6D", "Uso del claxon innecesario.", 6),
    ("7A", "Cuando no respetan señales de tráfico.", 7),
    ("7B", "Cuando bloquean el paso.", 7),
    ("7C", "Cuando realizan maniobras peligrosas.", 7),
    ("7D", "Cuando conducen distraídos.", 7),
    ("8A", "Mejoro mi actitud al volante.", 8),
    ("8B", "Planifico mi ruta con tiempo.", 8),
    ("8C", "Evito horas pico para conducir.", 8),
    ("8D", "Escucho música relajante.", 8),
    ("9A", "Conductores agresivos.", 9),
    ("9B", "Obstáculos inesperados en la vía.", 9),
    ("9C", "Condiciones climáticas adversas.", 9),
    ("9D", "Atascos prolongados.", 9),
    ("10A", "Cambio de ruta.", 10),
    ("10B", "Llamo a la persona que espero.", 10),
    ("10C", "Reviso el tráfico en mi GPS.", 10),
    ("10D", "Espero con paciencia.", 10),
    ("11A", "Conduzco en autopista.", 11),
    ("11B", "El tráfico es muy denso.", 11),
    ("11C", "Estoy manejando bajo presión.", 11),
    ("11D", "Tengo prisa por llegar.", 11),
    ("12A", "Cuando estoy detenido en un semáforo.", 12),
    ("12B", "Si otro conductor me adelanta sin motivo.", 12),
    ("12C", "Al conducir por zonas residenciales.", 12),
    ("12D", "En carreteras con curvas peligrosas.", 12),
    ("13A", "Me adelantan de forma temeraria.", 13),
    ("13B", "Bloquean la intersección sin motivo.", 13),
    ("13C", "Hacen maniobras peligrosas cerca de mi vehículo.", 13),
    ("13D", "No respetan las señales de tráfico.", 13),
    ("14A", "Reducen velocidad de forma inesperada.", 14),
    ("14B", "Cambian de carril sin señalizar.", 14),
    ("14C", "Utilizan indebidamente el claxon.", 14),
    ("14D", "Se estacionan en doble fila.", 14),
    ("15A", "Ante conductores agresivos.", 15),
    ("15B", "En atascos prolongados.", 15),
    ("15C", "Cuando hay obras en la vía.", 15),
    ("15D", "Si un peatón cruza imprudentemente.", 15),
    ("16A", "Cuando llevo pasajeros que me presionan.", 16),
    ("16B", "Si el tráfico es muy lento.", 16),
    ("16C", "Con clima adverso.", 16),
    ("16D", "Cuando otro conductor me cierra el paso.", 16),
    ("17A", "Al pasar por intersecciones peligrosas.", 17),
    ("17B", "En carreteras de montaña.", 17),
    ("17C", "Si hay poca visibilidad.", 17),
    ("17D", "Cuando hay vehículos pesados en la vía.", 17),
    ("18A", "Llamo a emergencias.", 18),
    ("18B", "Busco una salida alternativa.", 18),
    ("18C", "Espero pacientemente.", 18),
    ("18D", "Hago sonar el claxon repetidamente.", 18),
    ("19A", "Manejo a una velocidad moderada.", 19),
    ("19B", "Acelero para pasar lo más rápido posible.", 19),
    ("19C", "Busco un lugar seguro para estacionar.", 19),
    ("19D", "Utilizo las luces de emergencia.", 19),
    ("20A", "Me mantengo en mi carril.", 20),
    ("20B", "Hago señales al conductor que intenta adelantarme.", 20),
    ("20C", "Aumento la velocidad para evitar que me adelanten.", 20),
    ("20D", "Me detengo para dejarlo pasar.", 20),
    ("21A", "Sigue maniobrando sin inmutarse.", 21),
    ("21B", "Aparca lo más rápidamente posible, intentando no molestar a los demás.", 21),
    ("21C", "Reacciona de manera agresiva.", 21),
    ("21D", "Se marcha a otro lugar o deja pasar.", 21),
    ("22A", "Pasa si cree que no hay peligro.", 22),
    ("22B", "Se incorpora rápidamente sin parar.", 22),
    ("22C", "Cede el paso con paciencia.", 22),
    ("22D", "Si tiene prisa, no se detiene.", 22),
    ("23A", "Trata de indicarle que Ud. ha llegado antes y va a aparcar.", 23),
    ("23B", "Atraviesa su coche y discute el asunto.", 23),
    ("23C", "Reacciona agresivamente y toca el claxon.", 23),
    ("23D", "Busca, sin más, otro aparcamiento.", 23),
    ("24A", "Se pone nervioso y se impacienta.", 24),
    ("24B", "Hace caso del agente y se despreocupa del tema.", 24),
    ("24C", "Se detiene y espera.", 24),
    ("24D", "Si tarda un poco, le llama la atención de alguna manera.", 24),
    ("25A", "Si no ocurre nada, deja que siga.", 25),
    ("25B", "Reacciona de forma agresiva y le llama la atención.", 25),
    ("25C", "Hace que se detenga para pedirle explicaciones.", 25),
    ("25D", "Le adelanta y hace gestos insultantes.", 25),
    ("26A", "Adelanta, pase lo que pase.", 26),
    ("26B", "Deja que adelanten y se vayan.", 26),
    ("26C", "Recrimina la acción de los otros conductores.", 26),
    ("26D", "Se aguanta y espera para intentarlo de nuevo.", 26),
    ("27A", "Continúa, sin importarle la impaciencia del otro conductor.", 27),
    ("27B", "Pide disculpas y se pasa al otro carril.", 27),
    ("27C", "Reacciona con agresividad y acelera, sin ceder su posición.", 27),
    ("27D", "Se retira al otro carril.", 27),
    ("28A", "Se inquieta, pensando que ya ha hecho algo mal.", 28),
    ("28B", "Extrañado, se detiene, esperando ver lo que desea.", 28),
    ("28C", "Se detiene tranquilamente, seguro de no haber infringido ninguna norma de circulación.", 28),
    ("28D", "Se detiene y sale del coche dando un fuerte portazo y vocerando.", 28),
    ("29A", "Se siente molesto y le advierte de su actitud poco favorable para conducir.", 29),
    ("29B", "Le manda callar y, si persiste, detiene el coche.", 29),
    ("29C", "Tiene en cuenta alguna de sus observaciones.", 29),
    ("29D", "No hace caso a sus comentarios.", 29),
    ("30A", "Se intranquiliza y se inquieta al ver que nadie hace nada.", 30),
    ("30B", "Se llena de paciencia y espera.", 30),
    ("30C", "Adelanta por otro carril o por el arcén.", 30),
    ("30D", "Procura salir por la primera calle.", 30),
    ("31A", "Se impacienta y toca el claxon.", 31),
    ("31B", "Si lleva mucha prisa, procura buscar alguna solución o deja el coche aparcado y se va andando.", 31),
    ("31C", "Pacientemente espera y, si puede, cambia de ruta.", 31),
    ("31D", "Se enfurece y toca el claxon.", 31),
    ("32A", "Reacciona agresivamente.", 32),
    ("32B", "Se va a su derecha y deja pasar.", 32),
    ("32C", "Sigue a su aire sin importarle.", 32),
    ("32D", "Les indica que no puede ir más deprisa por alguna razón.", 32),
    ("33A", "Los recrimina y, si es posible, obstaculiza su paso.", 33),
    ("33B", "Espera tranquilamente.", 33),
    ("33C", "Si otros pasan, Ud. les sigue.", 33),
    ("33D", "Si lleva prisa, procura buscar una salida.", 33),
    ("34A", "Sigue su camino.", 34),
    ("34B", "Reitera el aviso y se retira lo más que puede a su derecha.", 34),
    ("34C", "Le obstaculiza el paso.", 34),
    ("34D", "Le recrimina agresivamente.", 34),
    ("35A", "Se detiene y le advierte de su imprudencia.", 35),
    ("35B", "Le increpa agresivamente.", 35),
    ("35C", "Le intenta asustar.", 35),
    ("35D", "Evita atropellarle y sigue su camino.", 35),
    ("36A", "Recrimina la acción del otro usuario.", 36),
    ("36B", "Discute y le hace saber de su enfado.", 36),
    ("36C", "Baja para ver los desperfectos e intenta dialogar sobre el tema.", 36),
    ("36D", "Reconoce su despiste y acepta sus reclamaciones.", 36),
    ("37A", "Intenta salir cortándoles el paso.", 37),
    ("37B", "Espera pacientemente que pasen.", 37),
    ("37C", "Les hace saber de alguna forma que debe esperar.", 37),
    ("37D", "Acelera intimidándoles.", 37),
    ("38A", "Reacciona de forma agresiva contra el conductor.", 38),
    ("38B", "Ve los daños y trata de llegar a un acuerdo con él.", 38),
    ("38C", "Le hace saber que él ha sido el culpable de lo sucedido.", 38),
    ("38D", "Trata de indicarle para que pague los desperfectos.", 38),
    ("39A", "Calmadamente le pide explicaciones.", 39),
    ("39B", "Le hace saber que él es el causante y que deberá ser su despiste.", 39),
    ("39C", "Se muestra agresivo y le recrimina su acción.", 39),
    ("39D", "Se muestra agresivo e intransigente y hace ademán de pegarle.", 39),
    ("40A", "Se disculpa e intenta convencerle de que no le sancione.", 40),
    ("40B", "Discute su actuación.", 40),
    ("40C", "Acepta la sanción sin rechistar.", 40),
    ("40D", "No hace caso de la multa.", 40),
    ("41A", "Acelera y pasa antes que ellos.", 41),
    ("41B", "Espera impaciente que pasen.", 41),
    ("41C", "Tranquilamente espera a que pase el último.", 41),
    ("41D", "Sigue la marcha con preocupación.", 41),
    ("42A", "Toca el claxon insistentemente y pasa a toda costa.", 42),
    ("42B", "Se muestra agresivo verbalmente o gestualmente.", 42),
    ("42C", "Critica su acción, pero espera.", 42),
    ("42D", "Le deja que se vaya.", 42),
    ("43A", "Procura anotar su matrícula y denunciarle.", 43),
    ("43B", "Se enfada mucho y le insulta aunque le oiga.", 43),
    ("43C", "Trata de alcanzarle y le hace parar.", 43),
    ("43D", "Se resigna, sin más.", 43),
    ("44A", "Le recrimina con gestos o palabras.", 44),
    ("44B", "Le indica que se retire al carril para vehículos lentos.", 44),
    ("44C", "Le adelanta, sin más.", 44),
    ("44D", "Espera pacientemente.", 44),
    ("45A", "Enfadado, recrimina su actuación.", 45),
    ("45B", "Procura ignorarlos o les pide que le dejen en paz.", 45),
    ("45C", "Si no le hacen caso, detiene el coche.", 45),
    ("45D", "Participa en su conversación y de sus bromas.", 45),
    ("46A", "Toca el claxon y recrimina su inexperiencia.", 46),
    ("46B", "Le indica que inicie la marcha.", 46),
    ("46C", "Se impacienta ante la tardanza.", 46),
    ("46D", "Tranquilamente espera a que inicie la marcha.", 46),
    ("47A", "Se enfada por ello y critica su actuación.", 47),
    ("47B", "Les deja que pasen.", 47),
    ("47C", "Les avisa para que le dejen incorporarse al tráfico.", 47),
    ("47D", "Atraviesa el coche haciéndoles frenar bruscamente.", 47),
    ("48A", "Se enfada mucho y toca reiteradamente el claxon.", 48),
    ("48B", "Al llegar el dueño le recrimina e insulta.", 48),
    ("48C", "Toca el claxon para avisar al propietario y espera con poco ruido.", 48),
    ("48D", "Acepta sus disculpas.", 48),
    ("49A", "Le avisa de su negligencia.", 49),
    ("49B", "Le insulta desde su coche.", 49),
    ("49C", "Si persiste, hace lo mismo que él.", 49),
    ("49D", "Se distrae, se inquieta y se resigna.", 49),
    ("50A", "Toca reiteradamente el claxon e intenta adelantar.", 50),
    ("50B", "Insulta e increpa su acción, pero no adelanta.", 50),
    ("50C", "Desiste de adelantar.", 50),
    ("50D", "Sigue la maniobra de adelantamiento y le insulta al pasar.", 50),
    ("51A", "Frena bruscamente para que se dé cuenta de que le están molestando las luces.", 51),
    ("51B", "Le deja pasar y hace lo mismo que él.", 51),
    ("51C", "Le hace señales para que se dé cuenta de que lleva luces largas.", 51),
    ("51D", "Aumenta la velocidad para dejarle atrás.", 51),
    ("52A", "Le deja pasar.", 52),
    ("52B", "Le hace retroceder, sin dudar.", 52),
    ("52C", "Le advierte de su error.", 52),
    ("52D", "Le increpa y le hace retroceder.", 52),
    ("53A", "No deja incorporarse a ninguno.", 53),
    ("53B", "Da paso a uno o dos.", 53),
    ("53C", "Recrimina su actuación y no deja pasar a ninguno.", 53),
    ("53D", "Si no tiene prisa, espera a que pasen.", 53),
    ("54A", "Intenta adelantar dando señales de luces.", 54),
    ("54B", "Aguanta pacientemente hasta que pueda hacerlo.", 54),
    ("54C", "Le hace señales para que le indique cuándo puede pasar.", 54),
    ("54D", "Adelanta sin más.", 54),
    ("55A", "Se disculpa de alguna forma.", 55),
    ("55B", "Continúa sin más.", 55),
    ("55C", "Se ríe y piensa que la culpa es de ellos.", 55),
    ("55D", "Tendrá cuidado de que no vuelva a pasar en otra ocasión.", 55),
    ("56A", "Intenta convencer al agente de que el retraso fue involuntario.", 56),
    ("56B", "Increpa al agente si no hace caso.", 56),
    ("56C", "Paga la multa y procura aparcar mejor otra vez.", 56),
    ("56D", "Se niega rotundamente a pagar la multa.", 56),
    ("57A", "Continúa a la misma velocidad, ya que tiene preferencia.", 57),
    ("57B", "Le hace señales para hacerle saber su presencia y preferencia.", 57),
    ("57C", "Le deja pasar si lo hace.", 57),
    ("57D", "Le insulta por su actitud.", 57),
], key=lambda x: (x[2], x[0]))  # Ordenar por idP (pregunta) y luego por idO (opción)

# Función para insertar las opciones en la base de datos MySQL
def insertar_opciones():
    try:
        print("Conectando a la base de datos MySQL...")
        conn = mysql.connector.connect(**db_config)
        cursor = conn.cursor()

        for idO, texto, idP in opciones:
            # Verificar si la opción ya existe
            cursor.execute('SELECT COUNT(*) FROM opciones WHERE idO = %s', (idO,))
            existe = cursor.fetchone()[0]

            if existe == 0:
                cursor.execute(
                    'INSERT INTO opciones (idO, texto, idP) VALUES (%s, %s, %s)',
                    (idO, texto, idP)
                )
                print(f"Opción con ID {idO} insertada correctamente.")
            else:
                print(f"Opción con ID {idO} ya existe. Saltando inserción.")

        conn.commit()
        print("¡Opciones nuevas insertadas correctamente en la base de datos!")

    except mysql.connector.Error as err:
        print(f"Error al insertar opciones: {err}")
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()
        print("Conexión a la base de datos cerrada.")

# Ejecutar la función si el archivo se ejecuta directamente
if __name__ == '__main__':
    insertar_opciones()